### ISSUE TITLE
Unknown Starting issue

### ISSUE THREAD

**Issue by Aidan360** [MJRLegends/MorePlanetsExtras#1]
So when i downloaded The extra Planets for galacticraft on my computer with the mods Forge,Galacticraft,Micdoodlecore,Galacticraftplanets, and with MjrLegendslib, i met a glich where when i loaded in with all the mods it took 10 secs in the loading in java where it was black and then it crashed and when i looked at what it said it said "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)" 
if you are able to tell me how to fix it please let me know.

Important info
Computer: Mac OSX
Minecraft Version: 1,12,2

**Comment by MJRLegends** [comment]
Please post full version of the log file. the one line you have copied and pasted means nothing. Also please include version numbers are i think you just have out dated versions of mods or downloaded them from a unofficial stolen source

maybe use this template i've added to new issues reports to make sure you have all needed info

```
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

```
