### ISSUE TITLE
Cant create space stations on related planets (Diona Nibiru Chalos)  AIR blocks instead of needed Resources

### ISSUE THREAD

**Issue by romashulman** [MJRLegends/MorePlanetsExtras#3]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

-Cant create space stations on related planets (Diona Nibiru Chalos) 
-AIR blocks instead of needed Resources

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/77308429/109373108-d5428780-7861-11eb-9e64-c6571294d6b5.png)

![image](https://user-images.githubusercontent.com/77308429/109373169-2c485c80-7862-11eb-8ac7-dd5f0aa96a30.png)

![image](https://user-images.githubusercontent.com/77308429/109373142-0de26100-7862-11eb-9e7b-060013d10ffd.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
-Mod Version MorePlanetsExtras-1.12.2-1.0

Minecraft Version 1.12.2
More-Planets-1.12.2-2.2.1-GC280

**Where did this bug happen:** [Single Player or Server]
-Single Player 
-LAN

### Additional Information
[Any other information that may be able to help me with the problem]

======================================================

**Comment by MJRLegends** [comment]
Please actually fill out the template
